language: cpp

compiler:
  - gcc
  - clang

script:
  - cd tests
  - git clone https://github.com/CxxTest/cxxtest.git cxxtest-ro
  - export PATH="$PATH:$(pwd)/cxxtest-ro/bin"
  - ln -s cxxtest-ro/cxxtest cxxtest
  - make && make test
